CREATE TABLE PERSONSTYPE (
   ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE PERSONS (
   ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_PERSONTYPE INT NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   IDCARD VARCHAR(50) UNIQUE,
   DOB DATE,
   FOREIGN KEY(ID_PERSONTYPE) REFERENCES PERSONSTYPE(ID) ON DELETE CASCADE
);

CREATE TABLE MEALS (
   ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   NAME VARCHAR(100) NOT NULL UNIQUE,
   VISIBLE BOOLEAN NOT NULL        
);

CREATE TABLE SERVINGS (
   ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_PERSON BIGINT NOT NULL,   
   ID_MEAL INT NOT NULL,
   DATE DATE NOT NULL,
   FOREIGN KEY(ID_MEAL) REFERENCES MEALS(ID) ON DELETE CASCADE
);                       

CREATE TABLE PERIODS (
   ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_PATIENT BIGINT NOT NULL,
   ID_COMPANION BIGINT,
   CHECKIN DATE DEFAULT CURRENT_DATE NOT NULL,
   CHECKOUT DATE,
   OBS clob(500),
   FOREIGN KEY(ID_PATIENT) REFERENCES PERSONS(ID) ON DELETE CASCADE 
);

CREATE TABLE REPORTS (
   ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_PERSON BIGINT NOT NULL,
   DATE DATE NOT NULL,
   DETAILED BOOLEAN,
   FOREIGN KEY(ID_PERSON) REFERENCES PERSONS(ID) ON DELETE CASCADE 
);

CREATE INDEX IDX_SERVINGS_ID_PERSON ON SERVINGS(ID_PERSON);    
CREATE INDEX IDX_PERIODS_ID_PATIENT ON PERIODS(ID_PATIENT);  
CREATE INDEX IDX_PERIODS_CHECKIN ON PERIODS(CHECKIN);          
 
 

INSERT INTO PERSONSTYPE (DESCRIPTION) VALUES ('Embarazada');
INSERT INTO PERSONSTYPE (DESCRIPTION) VALUES ('Acompañante');
INSERT INTO PERSONSTYPE (DESCRIPTION) VALUES ('Responsables');

INSERT INTO MEALS (NAME, VISIBLE) VALUES ('Desayuno', true);
INSERT INTO MEALS (NAME, VISIBLE) VALUES ('Almuerzo', true);
INSERT INTO MEALS (NAME, VISIBLE) VALUES ('Cena', true);
 